### ISSUE TITLE
Determine solution or official recommendation for autofill issues

### ISSUE THREAD

**Issue by javayoung** [cloudfour/hideShowPassword#15]
The plug in works so well. But it just has a weird issue. When the user name or the password input have not been set up with any value, it will automatically show the browser saved user name and password for the current webpage. Is there a way to not show browser saved user name and password? Thank you
![untitled](https://cloud.githubusercontent.com/assets/3420826/4393555/cf28d32e-4418-11e4-8fff-a8a1d45fe9de.png)

**Comment by simevidas** [comment]
I think the ideal implementation of the “Show password” feature would be as follows:

1. the control should initially be **disabled** (HTML `disabled` attribute)
2. when the user edits the password field for the first time, **confirm** the the current value has been produced from user input (i.e. it wasn’t autofilled), and only then enable the control

You can see this functionality in practice here: https://www.youtube.com/watch?v=Dt8np9kYCVM

@tylersticka Please consider adding this as an option.

**Comment by tylersticka** [comment]
Thanks, @simevidas! Do you have advice regarding this portion:

> when the user edits the password field for the first time, **confirm** the the current value has been produced from user input (i.e. it wasn’t autofilled)

Any advice on how one would reliably do that?
