### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/hideShowPassword#21]
See also: [Making your jQuery plugin work better with npm tools](http://blog.npmjs.org/post/112712169830/making-your-jquery-plugin-work-better-with-npm)

- [x] Revise module portion of JS to include Node/CommonJS
- [x] Add `package.json`
- [x] Add minification script to `package.json`
- [x] Resolve duplication between `package.json` and `bower.json`
- [x] Test npm/Browserify
- [x] Test Bower
- [x] Update README
- [x] Merge release
- [x] Tag release
- [x] [Publish](https://docs.npmjs.com/cli/publish)

**Comment by lyzadanger** [comment]
@tylersticka Lemme know if you'd like any help with this one. I've been doing some `npm` internal dives lately.

**Comment by tylersticka** [comment]
https://www.npmjs.com/package/hideShowPassword :tada:
