### ISSUE TITLE
Smaller wink image?

### ISSUE THREAD

**Issue by MB34** [cloudfour/hideShowPassword#26]
I'd like to see a 25% smaller wink image, about  the same size as the one in IE11.
![image](https://cloud.githubusercontent.com/assets/377196/7480987/6c468746-f332-11e4-9e53-f9e434f28e08.png)

**Comment by tylersticka** [comment]
@MB34 Thanks for your suggestion!

The included styles and images are just examples, and are provided under [an MIT license](http://www.opensource.org/licenses/MIT). You can make them smaller, larger or do something altogether different! The choice is yours. :smile:

**Comment by MB34** [comment]
The PNG looks kind of ragged. I'll see what I can do and donate them.

**Comment by tylersticka** [comment]
@MB34 You might have better luck with the SVG (the PNG is just an export of that asset).

**Comment by MB34** [comment]
I understand that I'll have to adjust the CSS values but I can't figure out where the right margin is getting set in the code.

**Comment by tylersticka** [comment]
@MB34 Check out the `toggle.offset` [option](https://github.com/cloudfour/hideShowPassword#options), which defaults to `0`. (For usability, it's best to keep this at `0` so clumsy fingers won't accidentally miss the toggle.)
