### ISSUE TITLE
How to ...

### ISSUE THREAD

**Issue by MB34** [cloudfour/hideShowPassword#27]
In your demo, the middle one has the password initially shown with a toggle. I want it initially masked, like in IE11 and have the show button showing. I don't see how to do that.

**Comment by tylersticka** [comment]
@MB34 That should work! If you don't need any extra options, you can also do...

```javascript
$('#example').hidePassword(true);

// or...

$('#example').hideShowPassword(false, true);
```

Check out [the README](https://github.com/cloudfour/hideShowPassword/blob/master/README.md) for more examples!
