### ISSUE TITLE
Npm package broken

### ISSUE THREAD

**Issue by jeremylevy** [cloudfour/hideShowPassword#28]
The NPM package seems to be broken :

```
npm install hideShowPassword
```
```
fetch failed https://registry.npmjs.org/hideShowPassword/-/hideShowPassword-2.0.4.tgz
npm ERR! Error: 404 Not Found
```

By the way, thanks for the good work. It works very well.

**Comment by tylersticka** [comment]
Hrm, I'm encountering the same error. Thanks for letting us know, we'll investigate...

**Comment by tylersticka** [comment]
Huh, it worked for me a moment ago, but for @erikjung it did not.

According to [NPM's Troubleshooting page](https://github.com/npm/npm/wiki/Troubleshooting#not-found--server-error):

> - It's most likely a temporary npm registry glitch. Check [npm server status](http://status.npmjs.org/) and try again later.
> - If the error persists, perhaps the published package is corrupt. Contact the package owner and have them publish a new version of the package.

But the status is currently green. The fact that it installs fine _some_ of the time (and if I do an `npm install ~/my/local/folder/hideShowPassword`, that works fine, too) suggests that _corruption_ is unlikely.

Some pages online say you need to set the `npm` registry, but running `npm get registry` for me outputs the correct registry URL.

Most perplexing, one of our other npm modules doesn't seem to have this problem at all...

Still investigating....... :thought_balloon:

**Comment by jeremylevy** [comment]
It worked for me BEFORE my npm cache was cleaned with:

```
npm cache clean
```

Once cleaned, the `npm install` has broken.

Thanks for the support !

**Comment by tylersticka** [comment]
Yeah, that seems to be the case for me as well... cleaning the cache makes it break again.

@lyzadanger pointed out that it's perplexing to see zero downloads [on the npm page](https://www.npmjs.com/package/hideShowPassword), compared to [another package](https://www.npmjs.com/package/leveller) which has many downloads despite being far less popular (it has about 1% of the amount of GitHub stars). Something's not right there!

**Comment by tylersticka** [comment]
I'm comparing the two `package.json` files and noticing a discrepancy in the way the `repository.url` field is specified.

For Leveller, it's defined as `https://github.com/cloudfour/leveller.git`.

For hideShowPassword, it's defined as `git://github.com/cloudfour/hideShowPassword.git`. 

The NPM docs [show examples](https://docs.npmjs.com/files/package.json#repository) that use the former (https), not the latter (git).

I'm going to modify the `package.json` and push a new version to see if that remedies the issue or not.

**Comment by tylersticka** [comment]
Did not mean to close this.

So, I implemented the package.json change, but then there's a new wrinkle... I found out that `npm` doesn't allow publishing of packages with capital letters in their names. I'm not sure how we got a registry page at all before, but apparently that was a fluke or an oversight or a hiccup or something.

Still developing...

**Comment by tylersticka** [comment]
@jeremylevy What a long, strange trip it's been! Thanks for bearing with us.

Can you try `npm install hideshowpassword` (all lower-case) and see if that resolves your issue?

**Comment by jeremylevy** [comment]
It works ! You rock ! :+1:

**Comment by tylersticka** [comment]
@jeremylevy Great, thanks so much for reporting this issue! It's embarrassing to think how long this npm package may have been broken. :sweat: 

I spoke with the folks at NPM and they recommended deprecating `hideShowPassword`. So now, if you attempt to install the camel-case version, you should see a warning that advises you to use the lowercase version instead:

```
$ npm install hideShowPassword
npm WARN deprecated hideShowPassword@2.0.4: use lowercase version: hideshowpassword
...
```

Closing this issue now!
