### ISSUE TITLE
Wrapper margins are still inherited even when not included in the wrapper object's inheritStyles array

### ISSUE THREAD

**Issue by raddevon** [cloudfour/hideShowPassword#34]
I've instantiated my hideShowPassword element not to inherit margin values (since they aren't inherited properly in Firefox. See issue #33.). However, the margins are still being specified on the wrapper element. Here's how I instantiated the element:

    $('#password').hideShowPassword(false, true, {
        wrapper: {
          inheritStyles: ['display', 'verticalAlign']
        }
    });

**Comment by tylersticka** [comment]
This is a great catch. I forgot that [jQuery.extend](http://api.jquery.com/jquery.extend/) also applies to arrays.

**Comment by tylersticka** [comment]
@raddevon This option is pretty gnarly as-is (we've got some open issues to streamline in the next version), but for now I think I've come up with a backwards-compatible quick-fix.

Could you give the version in the [fix-inheritStyles](https://github.com/cloudfour/hideShowPassword/tree/fix-inheritStyles) branch a try for me to verify whether or not it resolves your issue?

**Comment by raddevon** [comment]
@tylersticka Yes, this fixes it. Thank you for the quick fix!

**Comment by tylersticka** [comment]
Thanks, @raddevon !

I'm gonna re-open this issue until it's merged into `master`, just in case any other users are having the problem before then.
