### ISSUE TITLE
Rendering issue when displayed on a modal form.

### ISSUE THREAD

**Issue by w3MediaLabs** [cloudfour/hideShowPassword#38]
Hello.

When I display a form in a modal, the plugin rendering fails somehow.

Screen shot with plugin enabled on a modal dialog: 
![password-bad](https://cloud.githubusercontent.com/assets/7306696/9512036/3721d44a-4c4b-11e5-89a9-83653f424cbf.jpg)

Screen shot with plugin disabled on a modal dialog:
![password-good](https://cloud.githubusercontent.com/assets/7306696/9512040/4258718e-4c4b-11e5-8bf1-fbdc88ca3d5c.jpg)

Screen shot with plugin enabled, without modal dialog:
![password-good-no-modal](https://cloud.githubusercontent.com/assets/7306696/9512107/f68b44b0-4c4b-11e5-9339-826b55648d58.jpg)

And here is the initialization function:
```
// password reveals
$('#' + signupModelID +  '-password').hideShowPassword({
    show: false,
    innerToggle: true,
});
```

What do you think?

Thanks.

**Comment by tylersticka** [comment]
Hi, @w3MediaLabs ! Have you read the section of the README titled [Toggle Quirks in Invisible Elements](https://github.com/cloudfour/hideShowPassword#toggle-quirks-in-invisible-elements)? Also see issue #2 for a similar problem.

**Comment by w3MediaLabs** [comment]
Oops.. I did check the issues list, but only the open ones.

Sorry, I will look better.
