### ISSUE TITLE
Attach to hover event

### ISSUE THREAD

**Issue by lashnag** [cloudfour/hideShowPassword#47]
Hello, how can i attach hidePassword to hover event? I need show passord on mousedown and hide on mouseup.

**Comment by tylersticka** [comment]
If you use your own toggle markup, you can attach events to whatever element you like, calling the `showPassword`, `hidePassword` and/or `togglePassword` methods on the input element. See [this section of the README](https://github.com/cloudfour/hideShowPassword#showing-hiding-and-toggling).

**Comment by lashnag** [comment]
I already read it, ant try to use it like this:

.hideShowPassword({toggle : {attachToTouchEvent: 'mouseup.hideShowPassword mousedown.hideShowPassword'}});
But it doesn't wor
k
>Понедельник, 10 октября 2016, 19:13 +03:00 от Tyler Sticka <notifications@github.com>:
>
>If you use your own toggle markup, you can attach events to whatever element you like, calling the showPassword, hidePassword and/or togglePassword methods on the input element. See  this section of the README .
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, Лашнев Алексей

**Comment by tylersticka** [comment]
@lashnag You are using the wrong `attachTo*` option (there is no hover for touchscreens) and you are using `mouseup` and `mousedown` (which correspond to buttons) instead of `mouseenter` and `mouseleave`.

```js
$('input').hideShowPassword({
  innerToggle: true,
  toggle: {
    attachToEvent: 'mouseenter mouseleave'
  }
});
```

[CodePen here](http://codepen.io/tylersticka/pen/vXjRWa?editors=1010)

**Comment by lashnag** [comment]
It's worked! Thankyou!

>Вторник, 11 октября 2016, 20:00 +03:00 от Tyler Sticka <notifications@github.com>:
>
>@lashnag You are using the wrong attachTo* option (there is no hover for touchscreens) and you are using mouseup and mousedown (which correspond to buttons) instead of mouseenter and mouseleave.
>$('input').hideShowPassword({
  innerToggle: true,
  toggle: {
    attachToEvent: 'mouseenter mouseleave'
  }
});
>CodePen here
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, Лашнев Алексей
