### ISSUE TITLE
Can't change button title "Show Password"

### ISSUE THREAD

**Issue by lashnag** [cloudfour/hideShowPassword#48]
I used this code:

```
$('input[name="card_cvc"]').hidePassword({
          innerToggle: true,
          toggle: {
                        attachToEvent: 'mousedown mouseup',
                        attr: {
                            role: 'button',
                            'aria-label': 'Test',
                            title: 'Test',
                            tabIndex: 0
                        }
                    }
                });
```

But i saw title "Show Password" anyway.

> http://s020.radikal.ru/i708/1612/af/9168bf09e903.png

**Comment by tylersticka** [comment]
Hi @lashnag,

The root plugin settings only apply to the elements _before_ a state (shown or hidden) is applied. When a state is applied, options are overridden by the contents of `states.shown` or `states.hidden` in the settings object.

So if you wanted to customize the button content, title, etc. for both states, as well as the initial state prior to any of that being applied, it would look like this:

```js
$('input').hideShowPassword({
  innerToggle: true,
  toggle: {
    attachToEvent: 'mousedown mouseup',
    attr: {
      role: 'button',
      'aria-label': 'Test',
      title: 'Test',
      tabIndex: 0
    }
  },
  states: {
    shown: {
      toggle: {
        content: 'Shown!!',
        attr: {
          title: 'My Shown Title'
        }
      }
    },
    hidden: {
      toggle: {
        content: 'Hidden!!',
        attr: {
          title: 'My Hidden Title'
        }
      }
    }
  }
});
```

- [Live example here →](http://codepen.io/tylersticka/pen/aBQRVx?editors=0010)
- [Options section of README →](https://github.com/cloudfour/hideShowPassword#options)

**Comment by lashnag** [comment]
It's work! Thankyou!


>Четверг, 15 декабря 2016, 19:57 +03:00 от Tyler Sticka <notifications@github.com>:
>
>Hi  @lashnag ,
>The root plugin settings only apply to the elements  before a state (shown or hidden) is applied. When a state is applied, options are overridden by the contents of states.shown or states.hidden in the settings object.
>So if you wanted to customize the button content, title, etc. for both states, as well as the initial state prior to any of that being applied, it would look like this:
>$('input').hideShowPassword({
  innerToggle: true,
  toggle: {
    attachToEvent: 'mousedown mouseup',
    attr: {
      role: 'button',
      'aria-label': 'Test',
      title: 'Test',
      tabIndex: 0
    }
  },
  states: {
    shown: {
      toggle: {
        content: 'Shown!!',
        attr: {
          title: 'My Shown Title'
        }
      }
    },
    hidden: {
      toggle: {
        content: 'Hidden!!',
        attr: {
          title: 'My Hidden Title'
        }
      }
    }
  }
});
>*  Live example here →
>*  Options section of README →
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением, Лашнев Алексей
