### ISSUE TITLE
hideToggleUntil is not documented

### ISSUE THREAD

**Issue by MarcinOrlowski** [cloudfour/hideShowPassword#49]
Just FYI: `hideToggleUntil` option is not documented

**Comment by tylersticka** [comment]
Not sure I follow, as there is no `hideToggleUntil` option. You can set `innerToggle` to an event name and it will keep it hidden until that event. This is documented in the README [here](https://github.com/cloudfour/hideShowPassword#enabling-the-inner-toggle-button) and in the `innerToggle` portion [here](https://github.com/cloudfour/hideShowPassword#options).

**Comment by MarcinOrlowski** [comment]
Hm, you're right, but this is bit odd. I formerly found your script [here](http://www.jqueryscript.net/form/Toggle-Password-Visibility-With-jQuery-hideShowPassword.html) and I simply thought it's just the same code. Funny thing is that when you download it from there, then scripts links to your github but said `hideToggleUntil` is implemented in that code.

**Comment by tylersticka** [comment]
I haven't seen that website before, not sure who uploaded the code there but it appears to be hosting an outdated version of the plugin.

I just sent a message to the website's owners asking that they update or remove the outdated plugin. Apologies for the confusion... rest assured that the version here on GitHub and [on npm](https://www.npmjs.com/package/hideshowpassword) is actively maintained.
