### ISSUE TITLE
Some of the demo doesn't work on Windows 8.1 touchscreen PC in Chrome, Firefox

### ISSUE THREAD

**Issue by ArnaudDelafosse** [cloudfour/hideShowPassword#52]
In Firefox and Chrome, only the 3rd example on [the demo page](http://cloudfour.github.io/hideShowPassword/) (checkbox) works with keyboard action (Tab + Space bar ), not the 2 others.

**Comment by tylersticka** [comment]
Which version/OS of Chrome and Firefox did you test on? I just tried in Chrome 57 and Firefox 53 (both on a Mac) and tab + space works the same for all demos.

Here's a GIF I recorded of me using tab and space to toggle all three demos in Firefox:

![hsp-kb](https://cloud.githubusercontent.com/assets/69633/25625216/cb788324-2f10-11e7-8c93-89a591915096.gif)

**Comment by ArnaudDelafosse** [comment]
Sorry, was in a bit of a rush... I'm running Win8.1 and FF 53 + Chr 58 (both latest). 
Now check this out: in IE11.0.96 (also latest) they all work fine!

**Comment by tylersticka** [comment]
Still works for me in Windows 10, Chrome 58 (fresh install):

![hsp-kb-win](https://cloud.githubusercontent.com/assets/69633/25628424/ff7f60b6-2f1a-11e7-8742-784842ca2a2d.gif)

Same for Firefox 53 (also a fresh install).

Did you try in an incognito or private tab? Is it possible you have extensions enabled that could be the culprit?

**Comment by ArnaudDelafosse** [comment]
Now that's weird. No I'm using the "normal" tabs. Tried with uBlockOrigin disabled but that didn't change anything. I'm not running any crazy ext., just your regular front-end dev stuff.
Could it be the Win version? Is yours a native Win10 or a VM/Mac dual boot thing?

**Comment by tylersticka** [comment]
The GIF was captured in VMware Fusion.

I just switched over to a genuine desktop PC with Windows 10 installed traditionally, and I'm still unable to reproduce.

Were you able to try in a private or incognito window/tab? Can you reproduce on a different machine?

**Comment by ArnaudDelafosse** [comment]
I've tried in private tabs (FF + Chr) but I get the same behaviour and I don't have a Win10 machine handy. :/
I guess we'll just have to leave it at that for now. 
For info, today Win8.1 accounts for 10% of all Windows OS globally (see capt).
Good luck with that and cheers for the plugin regardless.
If I can be of any help, please let me know.
Arnaud
![winver](https://cloud.githubusercontent.com/assets/1129732/25656172/05ce6eca-2ff8-11e7-93f5-daf9b60804ae.png)

**Comment by tylersticka** [comment]
The plugin's keyboard accessibility hasn't changed since 2014 (see #6 and [this post](https://cloudfour.com/thinks/hideshowpassword-2/#improved-accessibility)), at which point Windows 8 was the most recent Windows version and was used extensively for testing. Without those accessibility features, it's doubtful that organizations like HP and Lucid Meetings would have adopted the plugin for their login forms.

I'm downloading a Windows 8.1 VM and will try on that OS specifically. But one thought that comes to mind: Is there any chance your PC has a touchscreen?

If so, can you tell me which of the inputs in this CodePen work for you via keyboard and which do not? https://s.codepen.io/tylersticka/debug/LyjbaO

**Comment by ArnaudDelafosse** [comment]
Interesting stuff...
First, on the [Lucid M log-in](https://meet.lucidmeetings.com/) form, it works just fine (space bar toggle). Yay!

Then yes I DO have a touchscreen laptop, it's this a Dell Inspiron 15.6" Ultra HD Touch-Screen. Do you suggest that because it's touch-enabled, it would 'cancel' the keyboard feature in some instances? 

Finally, on your Codepen the 1st and 3rd work fine with the space bar toggle. Hope that helps.

![codepen test](https://cloud.githubusercontent.com/assets/1129732/25671590/e0835e62-3030-11e7-8e0b-58e358144d75.png)

**Comment by tylersticka** [comment]
> Then yes I DO have a touchscreen laptop, it's a Dell Inspiron 15.6" Ultra HD Touch-Screen. Do you suggest that because it's touch-enabled, it would 'cancel' the keyboard feature in some instances?

It _shouldn't_, but it's always possible.

> Finally, on your Codepen the 1st and 3rd work fine with the space bar toggle. Hope that helps.
[edit] I should perhaps mention that they all 3 work on touch action

Well, this kinda dashes my hopes that I'd found the key to reproducing the issue, because this is exactly what I experience. It's _particularly_ odd that the first example works for you because it's using the default behavior, which should be the same as the demos. So what could possibly make the demos work in the CodePen but not in the demo page?

Off the top of my head, there are two possibilities. Sorry to continue using you as a guinea pig, but I'd love if you could try both of these ideas...

1. It could be that the demo we link to is not `https` by default. Try [this version](https://cloudfour.github.io/hideShowPassword/) and see if it works.
1. It could be that the Modernizr or even the jQuery behavior has been updated and our demo's versions of those libraries are too far out of date now. Can you try this pen which uses the same Modernizr and jQuery versions as our demo and tell me if any of the examples aren't working for you? http://s.codepen.io/tylersticka/debug/GmvrXK

**Comment by ArnaudDelafosse** [comment]
> Sorry to continue using you as a guinea pig, but I'd love if you could try both of these ideas...

Don't worry I'm more than happy to help. You did some great work and I can't wait to see it work 100% to promote/use it :)

> It could be that the demo we link to is not https by default. Try this version and see if it works.

Same: only the 3rd one works w space bar toggle

> It could be that the Modernizr or even the jQuery behavior has been updated and our demo's versions of those libraries are too far out of date now. Can you try this pen which uses the same Modernizr and jQuery versions as our demo and tell me if any of the examples aren't working for you? https://s.codepen.io/tylersticka/debug/GmvrXK

Now only the 3rd one works. You got a lead there
![codepen test2](https://cloud.githubusercontent.com/assets/1129732/25673075/7286dea6-3036-11e7-9171-9780896cfe73.png)

**Comment by tylersticka** [comment]
Yay! So my new hypothesis is that Modernizr updated their `touchevents` test to account for touchscreen PCs (or something symptomatic on a touchscreen PC), and it's probably been a zillion years since we updated the version of Modernizr in the demo, resulting in weird behavior.

**Comment by ArnaudDelafosse** [comment]
![gadg](https://cloud.githubusercontent.com/assets/1129732/25673595/3dd15f4a-3038-11e7-8dd9-9d98b90ecc2e.jpg)

**Comment by tylersticka** [comment]
@ArnaudDelafosse The demo dependencies have been updated! If you have a moment, would you mind doing a hard refresh of https://cloudfour.github.io/hideShowPassword/ and reporting back on whether or not the demos are working as expected?

**Comment by ArnaudDelafosse** [comment]
Hi Tyler, I'm afraid it's the same result (2 first fail and 3rd is OK) in FF and Chr with the cache emptied (modernizr 3.5.0 (Custom Build) + jQuery v3.2.1)
In IE all good.

**Comment by tylersticka** [comment]
Well, crud. Why in the world would that be? 😕

**Comment by ArnaudDelafosse** [comment]
Just a thought, on the [Lucid M log-in form](https://meet.lucidmeetings.com/) (which works), the toggle btn is a `<a>` with a `role="button"` instead of a `<button>`. Even though it's not semantically _ideal_, is it equivalent on a a11y level (AT)? That could be one way to fix this situation.

**Comment by tylersticka** [comment]
@ArnaudDelafosse Okay, trying to narrow this down to see if the dependency thing is a red herring or if it has something to do with the demo specifically.

I just put the exact demo source into a CodePen project, but replaced the Modernizr and jQuery references with the exact same ones my earlier CodePen is using (the one that seemed to work fine).

If this _doesn't_ work, then the dependencies may not be the issue... it may be _something_ about the demo page that's throwing it off.

If it _does_ work, then it could be something to do with a particular Modernizr version or perhaps some test we're not overtly using needs to be included.

In any event, if you could give this a whirl and report back, I'd sure appreciate it: https://b2d0cb5a0af348538d9801cb0f40ecd1.codepen.website/

**Comment by ArnaudDelafosse** [comment]
It WORKS !!  All three and in FF and Chrome.

**Comment by tylersticka** [comment]
Great! So now we just need to figure out why full Modernizr 2.8.3 on a CDN works, but a custom Modernizr 3.5.0 hosted relative to the file does not.

**Comment by ArnaudDelafosse** [comment]
I didn't have the time to check but did you use a customized ver of Modernizr for weight file reasons? Would it be too much of an assumption to think that most ppl would use your plugin within a project where the latest default Modernizr is already served by default via CDN?

**Comment by tylersticka** [comment]
@ArnaudDelafosse Modernizr recommends using a custom build, so we were following that approach. That said, the purpose of this library isn't to solve input detection (we're not smart enough) but to provide the right usability tools and some thoughtful defaults. So with that in mind, the demo has now been updated to offload those dependencies to a CDN in much the same way that CodePen does.

If you have a moment, we'd appreciate you refreshing the demo and giving it a try: http://cloudfour.github.io/hideShowPassword/

**Comment by ArnaudDelafosse** [comment]
I confirm it now works like a charm in both FF & Chr in Win8.1 with keyb navigation, mouse and touch.
Well done, I'll be more than happy to use it when needed and promote it.
Cheers

**Comment by tylersticka** [comment]
@ArnaudDelafosse Splendid! Thanks for your help and patience diagnosing, we really appreciate it. 🙂
