### ISSUE TITLE
jquery dependency in wordpress

### ISSUE THREAD

**Issue by artur822** [cloudfour/hideShowPassword#57]
I tried using this plugin for a form created by a the ultimate member plugin I included the hideshowPassword plugin in the footer of the page except for the jquery dependency which is already in use througn my functions.php file but it doesnt work and if I add the jquery dependency script in the footer of the page the form completely disapears.

**Comment by tylersticka** [comment]
What version of jQuery are you using? (If you're using the one that ships with WordPress, you can let us know your WordPress version instead.)

Where are you initializing the plugin, and can you share the code you're using to do so? (The plugin doesn't do anything unless initialized.)

Is there any sort of error in the dev tools console?

**Comment by tylersticka** [comment]
Closing this due to lack of further information.
