### ISSUE TITLE
Configure globally

### ISSUE THREAD

**Issue by bytestream** [cloudfour/hideShowPassword#60]
It would be good if we could set global defaults for the configuration, particularly for localisation of Show/Hide

`$.fn.hideShowPassword.defaults = {...}`

I think it would just be a simple case of adding `$.extend({}, $.fn.hideShowPassword.defaults, params)` here https://github.com/cloudfour/hideShowPassword/blob/master/hideShowPassword.js#L198

**Comment by bytestream** [comment]
@tylersticka happy to submit a PR if you agree

**Comment by tylersticka** [comment]
@bytestream Sure, sounds good!

**Comment by bytestream** [comment]
Sent :)

**Comment by tylersticka** [comment]
@bytestream Your PR (#61) has been merged, and the change is now available in version `2.2.0` of this package. Thank you for your contribution!

**Comment by bytestream** [comment]
Awesome! Thanks for the fast turnaround.
