### ISSUE TITLE
Classes should be in kebab-case

### ISSUE THREAD

**Issue by garak** [cloudfour/hideShowPassword#65]
Validation of css to use with this library (via stylelint and stylelint-config-standard) detects the following errora:

```
 ✖  Expected class selector ".hideShowPassword-toggle" to be kebab-case  selector-class-pattern
 ✖  Expected class selector ".hideShowPassword-field" to be kebab-case   selector-class-pattern
```
classes should be renamed like ".hide-show-password-toggle" and ".hide-show-password-field"

**Comment by tylersticka** [comment]
The sample CSS is included as a starting point. You may use whatever class names you'd like by specifying [the various `className` options](https://github.com/cloudfour/hideShowPassword#options) in accordance with your project's lint configuration.
